select 
    cast(match_area_id as integer) as match_area_id,
    match_area_name,
    match_area_code,
    match_competition_id,
    match_competition_name,
    match_competition_code,
    match_season_id,
    cast(match_season_start_date as date) as match_season_start_date,
    cast(match_season_end_date as date) as match_season_end_date,
    match_season_current_matchday,
    match_season_winner,
    cast(match_id as integer) as match_id,
    cast(match_utc_date as datetime) as match_utc_date,
    match_status,
    match_matchday,
    match_stage,
    match_group,
    cast(match_home_team_id as integer) as match_home_team_id,
    match_home_team_name,
    cast(match_away_team_id as integer) as match_away_team_id,
    match_away_team_name,
    cast(match_score_half_time_home as integer) as match_score_half_time_home,
    match_score_full_time_home,
    cast(match_score_half_time_away as integer) as match_score_half_time_away,
    match_score_full_time_away,
    match_referee
from {{ source('footydata_eng_raw', 'matches') }}
